# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannervideo',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
