# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20170720_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannervideo',
            old_name='url',
            new_name='video_code',
        ),
    ]
