# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:30
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/'),
        ),
    ]
