# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:23
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170718_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='photos/'),
        ),
    ]
