# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:26
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170718_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
